///Lista de campos existentes na ficha de utilizador
const List<String> listaCampos = [
  'strCartaoCidadao',
  'strCategoria',
  'strCodigoPostal',
  'strContatoEmergencia',
  'strContatoEmergencia2',
  'strDataNascimento',
  'strEstado',
  'strLocalidade',
  'strMorada',
  'strMorada2',
  'strNIF',
  'strPais',
  'strSexo',
  'strTelefone',
  'strTelemovel',
];

/// Lista de Generos existentes na ficha de utilizador
const List<String> listaGeneros = ['Masculino', 'Feminino'];

/// Lista de Paises existentes na ficha de utilizador
const List<Map<String, String>> listaPaises = [
  {'codigo': 'AF', 'nome': 'Afeganistão'},
  {'codigo': 'ZA', 'nome': 'África do Sul'},
  {'codigo': 'AL', 'nome': 'Albânia'},
  {'codigo': 'DE', 'nome': 'Alemanha'},
  {'codigo': 'AD', 'nome': 'Andorra'},
  {'codigo': 'AO', 'nome': 'Angola'},
  {'codigo': 'AI', 'nome': 'Anguilla'},
  {'codigo': 'AQ', 'nome': 'Antártida'},
  {'codigo': 'AG', 'nome': 'Antígua e Barbuda'},
  {'codigo': 'AN', 'nome': 'Antilhas Holandesas'},
  {'codigo': 'SA', 'nome': 'Arábia Saudita'},
  {'codigo': 'DZ', 'nome': 'Argélia'},
  {'codigo': 'AR', 'nome': 'Argentina'},
  {'codigo': 'AM', 'nome': 'Armênia'},
  {'codigo': 'AW', 'nome': 'Aruba'},
  {'codigo': 'AU', 'nome': 'Austrália'},
  {'codigo': 'AT', 'nome': 'Áustria'},
  {'codigo': 'AZ', 'nome': 'Azerbaijão'},
  {'codigo': 'BS', 'nome': 'Bahamas'},
  {'codigo': 'BH', 'nome': 'Bahrein'},
  {'codigo': 'BD', 'nome': 'Bangladesh'},
  {'codigo': 'BB', 'nome': 'Barbados'},
  {'codigo': 'BE', 'nome': 'Bélgica'},
  {'codigo': 'BZ', 'nome': 'Belize'},
  {'codigo': 'BJ', 'nome': 'Benin'},
  {'codigo': 'BM', 'nome': 'Bermudas'},
  {'codigo': 'BY', 'nome': 'Bielorrússia'},
  {'codigo': 'BO', 'nome': 'Bolívia'},
  {'codigo': 'BA', 'nome': 'Bósnia e Herzegovina'},
  {'codigo': 'BW', 'nome': 'Botsuana'},
  {'codigo': 'BR', 'nome': 'Brasil'},
  {'codigo': 'BN', 'nome': 'Brunei'},
  {'codigo': 'BG', 'nome': 'Bulgária'},
  {'codigo': 'BF', 'nome': 'Burkina Faso'},
  {'codigo': 'BI', 'nome': 'Burundi'},
  {'codigo': 'BT', 'nome': 'Butão'},
  {'codigo': 'CV', 'nome': 'Cabo Verde'},
  {'codigo': 'CM', 'nome': 'Camarões'},
  {'codigo': 'KH', 'nome': 'Camboja'},
  {'codigo': 'CA', 'nome': 'Canadá'},
  {'codigo': 'QA', 'nome': 'Catar'},
  {'codigo': 'KZ', 'nome': 'Cazaquistão'},
  {'codigo': 'TD', 'nome': 'Chade'},
  {'codigo': 'CL', 'nome': 'Chile'},
  {'codigo': 'CN', 'nome': 'China'},
  {'codigo': 'CY', 'nome': 'Chipre'},
  {'codigo': 'CX', 'nome': 'Christmas Island'},
  {'codigo': 'VA', 'nome': 'Cidade do Vaticano'},
  {'codigo': 'CC', 'nome': 'Cocos (Keeling) Islands'},
  {'codigo': 'CO', 'nome': 'Colômbia'},
  {'codigo': 'KM', 'nome': 'Comores'},
  {'codigo': 'CD', 'nome': 'Congo, República Democrática do'},
  {'codigo': 'CG', 'nome': 'Congo, República do'},
  {'codigo': 'CK', 'nome': 'Cook Islands'},
  {'codigo': 'KR', 'nome': 'Coréia, República da'},
  {'codigo': 'KP', 'nome': 'Coréia, República Democrática da'},
  {'codigo': 'CI', 'nome': 'Costa do Marfim'},
  {'codigo': 'CR', 'nome': 'Costa Rica'},
  {'codigo': 'HR', 'nome': 'Croácia'},
  {'codigo': 'CU', 'nome': 'Cuba'},
  {'codigo': 'DK', 'nome': 'Dinamarca'},
  {'codigo': 'DJ', 'nome': 'Djibouti'},
  {'codigo': 'DM', 'nome': 'Dominica'},
  {'codigo': 'EG', 'nome': 'Egito'},
  {'codigo': 'SV', 'nome': 'El Salvador'},
  {'codigo': 'AE', 'nome': 'Emirados Árabes Unidos'},
  {'codigo': 'EC', 'nome': 'Equador'},
  {'codigo': 'ER', 'nome': 'Eritréia'},
  {'codigo': 'SK', 'nome': 'Eslováquia (República Eslovaca)'},
  {'codigo': 'SI', 'nome': 'Eslovênia'},
  {'codigo': 'ES', 'nome': 'Espanha'},
  {'codigo': 'US', 'nome': 'Estados Unidos'},
  {'codigo': 'EE', 'nome': 'Estônia'},
  {'codigo': 'ET', 'nome': 'Etiópia'},
  {'codigo': 'FO', 'nome': 'Falkland Islands (Malvinas)'},
  {'codigo': 'FJ', 'nome': 'Fiji'},
  {'codigo': 'PH', 'nome': 'Filipinas'},
  {'codigo': 'FI', 'nome': 'Finlândia'},
  {'codigo': 'FR', 'nome': 'França'},
  {'codigo': 'GA', 'nome': 'Gabão'},
  {'codigo': 'GM', 'nome': 'Gâmbia'},
  {'codigo': 'GH', 'nome': 'Gana'},
  {'codigo': 'GE', 'nome': 'Geórgia'},
  {'codigo': 'GS', 'nome': 'Geórgia do Sul e Sandwich do Sul'},
  {'codigo': 'GI', 'nome': 'Gibraltar'},
  {'codigo': 'GD', 'nome': 'Granada'},
  {'codigo': 'GR', 'nome': 'Grécia'},
  {'codigo': 'GL', 'nome': 'Groelândia'},
  {'codigo': 'GP', 'nome': 'Guadalupe'},
  {'codigo': 'GU', 'nome': 'Guam'},
  {'codigo': 'GT', 'nome': 'Guatemala'},
  {'codigo': 'GG', 'nome': 'Guernsey'},
  {'codigo': 'GY', 'nome': 'Guiana'},
  {'codigo': 'GF', 'nome': 'Guiana Francesa'},
  {'codigo': 'GN', 'nome': 'Guiné'},
  {'codigo': 'GW', 'nome': 'Guiné Bissau'},
  {'codigo': 'GQ', 'nome': 'Guiné Equatorial'},
  {'codigo': 'HT', 'nome': 'Haiti'},
  {'codigo': 'HN', 'nome': 'Honduras'},
  {'codigo': 'HK', 'nome': 'Hong Kong'},
  {'codigo': 'HU', 'nome': 'Hungria'},
  {'codigo': 'YE', 'nome': 'Iémen'},
  {'codigo': 'BV', 'nome': 'Ilha Bouvet'},
  {'codigo': 'IM', 'nome': 'Ilha do Homem'},
  {'codigo': 'NF', 'nome': 'Ilha Norfolk'},
  {'codigo': 'KY', 'nome': 'Ilhas Cayman'},
  {'codigo': 'CK', 'nome': 'Ilhas Cook'},
  {'codigo': 'AX', 'nome': 'Ilhas de Aland'},
  {'codigo': 'HM', 'nome': 'Ilhas Heard e McDonald'},
  {'codigo': 'FO', 'nome': 'Ilhas Faroe'},
  {'codigo': 'FK', 'nome': 'Ilhas Malvinas'},
  {'codigo': 'MP', 'nome': 'Ilhas Marianas do Norte'},
  {'codigo': 'MH', 'nome': 'Ilhas Marshall'},
  {'codigo': 'SB', 'nome': 'Ilhas Salomão'},
  {'codigo': 'TC', 'nome': 'Ilhas Turks e Caicos'},
  {'codigo': 'VG', 'nome': 'Ilhas Virgens (Britânicas)'},
  {'codigo': 'VI', 'nome': 'Ilhas Virgens (U.S.)'},
  {'codigo': 'IN', 'nome': 'Índia'},
  {'codigo': 'ID', 'nome': 'Indonésia'},
  {'codigo': 'IR', 'nome': 'Irã (República Islâmica do)'},
  {'codigo': 'IQ', 'nome': 'Iraque'},
  {'codigo': 'IE', 'nome': 'Irlanda'},
  {'codigo': 'IS', 'nome': 'Islândia'},
  {'codigo': 'IL', 'nome': 'Israel'},
  {'codigo': 'IT', 'nome': 'Itália'},
  {'codigo': 'JM', 'nome': 'Jamaica'},
  {'codigo': 'JP', 'nome': 'Japão'},
  {'codigo': 'JE', 'nome': 'Jersey'},
  {'codigo': 'JO', 'nome': 'Jordânia'},
  {'codigo': 'KI', 'nome': 'Kiribati'},
  {'codigo': 'KW', 'nome': 'Kuwait'},
  {'codigo': 'LA', 'nome': 'Laos'},
  {'codigo': 'LS', 'nome': 'Lesoto'},
  {'codigo': 'LV', 'nome': 'Letônia'},
  {'codigo': 'LB', 'nome': 'Líbano'},
  {'codigo': 'LR', 'nome': 'Libéria'},
  {'codigo': 'LY', 'nome': 'Líbia'},
  {'codigo': 'LI', 'nome': 'Liechtenstein'},
  {'codigo': 'LT', 'nome': 'Lituânia'},
  {'codigo': 'LU', 'nome': 'Luxemburgo'},
  {'codigo': 'MO', 'nome': 'Macau'},
  {'codigo': 'MK', 'nome': 'Macedônia'},
  {'codigo': 'MG', 'nome': 'Madagascar'},
  {'codigo': 'MY', 'nome': 'Malásia'},
  {'codigo': 'MW', 'nome': 'Malawi'},
  {'codigo': 'MV', 'nome': 'Maldivas'},
  {'codigo': 'ML', 'nome': 'Mali'},
  {'codigo': 'MT', 'nome': 'Malta'},
  {'codigo': 'MA', 'nome': 'Marrocos'},
  {'codigo': 'MQ', 'nome': 'Martinica'},
  {'codigo': 'MU', 'nome': 'Maurício'},
  {'codigo': 'MR', 'nome': 'Mauritânia'},
  {'codigo': 'YT', 'nome': 'Mayotte'},
  {'codigo': 'MX', 'nome': 'México'},
  {'codigo': 'FM', 'nome': 'Micronésia'},
  {'codigo': 'MZ', 'nome': 'Moçambique'},
  {'codigo': 'MD', 'nome': 'Moldávia'},
  {'codigo': 'MC', 'nome': 'Mônaco'},
  {'codigo': 'MN', 'nome': 'Mongólia'},
  {'codigo': 'ME', 'nome': 'Montenegro'},
  {'codigo': 'MS', 'nome': 'Montserrat'},
  {'codigo': 'MM', 'nome': 'Myanmar'},
  {'codigo': 'NA', 'nome': 'Namíbia'},
  {'codigo': 'NR', 'nome': 'Nauru'},
  {'codigo': 'NP', 'nome': 'Nepal'},
  {'codigo': 'NI', 'nome': 'Nicarágua'},
  {'codigo': 'NE', 'nome': 'Níger'},
  {'codigo': 'NG', 'nome': 'Nigéria'},
  {'codigo': 'NU', 'nome': 'Niue'},
  {'codigo': 'NO', 'nome': 'Noruega'},
  {'codigo': 'NC', 'nome': 'Nova Caledônia'},
  {'codigo': 'NZ', 'nome': 'Nova Zelândia'},
  {'codigo': 'OM', 'nome': 'Omã'},
  {'codigo': 'NL', 'nome': 'Países Baixos'},
  {'codigo': 'BQ', 'nome': 'Países Baixos Caribenhos'},
  {'codigo': 'PW', 'nome': 'Palau'},
  {'codigo': 'PA', 'nome': 'Panamá'},
  {'codigo': 'PG', 'nome': 'Papua Nova Guiné'},
  {'codigo': 'PK', 'nome': 'Paquistão'},
  {'codigo': 'PY', 'nome': 'Paraguai'},
  {'codigo': 'PE', 'nome': 'Peru'},
  {'codigo': 'PN', 'nome': 'Pitcairn'},
  {'codigo': 'PF', 'nome': 'Polinésia Francesa'},
  {'codigo': 'PL', 'nome': 'Polônia'},
  {'codigo': 'PR', 'nome': 'Porto Rico'},
  {'codigo': 'PT', 'nome': 'Portugal'},
  {'codigo': 'QA', 'nome': 'Qatar'},
  {'codigo': 'KE', 'nome': 'Quênia'},
  {'codigo': 'KG', 'nome': 'Quirguistão'},
  {'codigo': 'CF', 'nome': 'República Centro-Africana'},
  {'codigo': 'DO', 'nome': 'República Dominicana'},
  {'codigo': 'RE', 'nome': 'Reunião'},
  {'codigo': 'RO', 'nome': 'Romênia'},
  {'codigo': 'RW', 'nome': 'Ruanda'},
  {'codigo': 'RU', 'nome': 'Rússia (Federação Russa)'},
  {'codigo': 'EH', 'nome': 'Saara Ocidental'},
  {'codigo': 'WS', 'nome': 'Samoa'},
  {'codigo': 'AS', 'nome': 'Samoa Americana'},
  {'codigo': 'SM', 'nome': 'San Marino'},
  {'codigo': 'SH', 'nome': 'Santa Helena'},
  {'codigo': 'LC', 'nome': 'Santa Lúcia'},
  {'codigo': 'PM', 'nome': 'São Pedro e Miquelon'},
  {'codigo': 'VC', 'nome': 'São Vicente e Granadinas'},
  {'codigo': 'KN', 'nome': 'Senegal'},
  {'codigo': 'SL', 'nome': 'Serra Leoa'},
  {'codigo': 'RS', 'nome': 'Sérvia'},
  {'codigo': 'SC', 'nome': 'Seychelles'},
  {'codigo': 'SG', 'nome': 'Singapura'},
  {'codigo': 'SY', 'nome': 'Síria'},
  {'codigo': 'SO', 'nome': 'Somália'},
  {'codigo': 'LK', 'nome': 'Sri Lanka'},
  {'codigo': 'SZ', 'nome': 'Suazilândia'},
  {'codigo': 'SD', 'nome': 'Sudão'},
  {'codigo': 'SE', 'nome': 'Suécia'},
  {'codigo': 'CH', 'nome': 'Suíça'},
  {'codigo': 'SR', 'nome': 'Suriname'},
  {'codigo': 'SJ', 'nome': 'Svalbard e Jan Mayen'},
  {'codigo': 'TH', 'nome': 'Tailândia'},
  {'codigo': 'TW', 'nome': 'Taiwan'},
  {'codigo': 'TJ', 'nome': 'Tajiquistão'},
  {'codigo': 'TZ', 'nome': 'Tanzânia'},
  {'codigo': 'IO', 'nome': 'Território Britânico do Oceano Índico'},
  {'codigo': 'TF', 'nome': 'Territórios Franceses do Sul'},
  {'codigo': 'PS', 'nome': 'Territórios Ocupados da Palestina'},
  {'codigo': 'TL', 'nome': 'Timor Leste'},
  {'codigo': 'TG', 'nome': 'Togo'},
  {'codigo': 'TK', 'nome': 'Tokelau'},
  {'codigo': 'TO', 'nome': 'Tonga'},
  {'codigo': 'TT', 'nome': 'Trinidad e Tobago'},
  {'codigo': 'TN', 'nome': 'Tunísia'},
  {'codigo': 'TM', 'nome': 'Turcomenistão'},
  {'codigo': 'TR', 'nome': 'Turquia'},
  {'codigo': 'TV', 'nome': 'Tuvalu'},
  {'codigo': 'UA', 'nome': 'Ucrânia'},
  {'codigo': 'UG', 'nome': 'Uganda'},
  {'codigo': 'UY', 'nome': 'Uruguai'},
  {'codigo': 'UZ', 'nome': 'Uzbequistão'},
  {'codigo': 'VU', 'nome': 'Vanuatu'},
  {'codigo': 'VE', 'nome': 'Venezuela'},
  {'codigo': 'VN', 'nome': 'Vietnã'},
  {'codigo': 'WF', 'nome': 'Wallis e Futuna'},
  {'codigo': 'ZM', 'nome': 'Zâmbia'},
  {'codigo': 'ZW', 'nome': 'Zimbábue'},
];
